module DeepL
  enum Action : UInt8
    TranslateText
    RephraseText
    CorrectText
    TranslateDocument
    TranslateDocumentUpload
    TranslateDocumentStatus
    TranslateDocumentDownload
    CreateGlossary
    DeleteGlossaryByName
    DeleteGlossaryById
    EditGlossaryByName
    EditGlossaryById
    OutputGlossaryEntriesByName
    OutputGlossaryEntriesById
    ListGlossaries
    ListGlossariesLong
    ListTranslationMemories
    ShowTranslationMemory
    ListTranslationMemorySegments
    ImportTranslationMemory
    ExportTranslationMemory
    ShowTranslationMemoryJob
    DeleteTranslationMemory
    ListFromLanguages
    ListTargetLanguages
    RetrieveUsage
    Version
    Help
  end
end
